### ISSUE TITLE
Error To Compile Driver

### ISSUE THREAD

**Issue by Zetolac** [btbd/modmap#12]
### Error To Compile Driver

**C2220 : The following warning is treated as an error
Warning C4996 'ExAllocatePool': has been declared inadvisable**

```
PSYSTEM_MODULE_INFORMATION modules = ExAllocatePool(NonPagedPool, size);
if (!modules) {
	return addr;
	}
```

How to fix this ?
Thanks,

**Comment by btbd** [comment]
@Zetolac Don't treat warnings as errors, add a warning disable for 4996 around it, or change all `ExAllocatePool`s to `ExAllocatePoolWithTag`.
