### ISSUE TITLE
Driver and dll loaded but  failed to find module!

### ISSUE THREAD

**Issue by Dexooma** [btbd/modmap#14]
The driver is loaded and get called & the process have the targ. dll loaded... idk why it still doing that.
I know that the driver get called with a valid "DATA_UNIQUE" and do the call request. 
[https://i.imgur.com/fQ1ITqL.png](url)

**Comment by btbd** [comment]
@Dexooma Are you sure the driver was successfully loaded? Check for debug output. The CLI app will always fail to find the module if it cannot communicate with the driver.
