### ISSUE TITLE
Failed to find module dxgi.dll

### ISSUE THREAD

**Issue by Seabear0628** [btbd/modmap#15]
Hello
 
im using modmap to inject a dll into FortniteClient-Win64-Shipping.exe using dxgi.dll as the target module but when i try to inject im given this error.

![image](https://user-images.githubusercontent.com/59465603/83366050-29234d00-a372-11ea-86b0-a9f8650688e9.png)

My driver mapper is correctly mapping the vulnerable driver for fortnite but im still getting this.

If anyone knows a fix it would be greatly appreciated.

**Comment by btbd** [comment]
Make sure the driver is actually being successfully loaded. See #7 and #14.
