### ISSUE TITLE
hi, modmap don`t working for hl.exe(counter-strike 1.6)

### ISSUE THREAD

**Issue by xSanx** [btbd/modmap#9]
I install your driver with OSRLoader. The driver tries to inject itself into the process, for example, in paint, but cannot find any dlls in the hl.exe process (error c0000225) Thanks

**Comment by btbd** [comment]
@xSanx Is the driver successfully loading? Is the game 32-bit?

**Comment by xSanx** [comment]
Yes, the driver downloaded using osrload. hl.exe 32-bit....

**Comment by btbd** [comment]
@xSanx 32-bit target process/DLL is not supported. See the README and https://github.com/btbd/modmap/issues/2.

**Comment by xSanx** [comment]
can I somehow rebuild the project for win32 applications?

**Comment by zxd1994** [comment]
> can I somehow rebuild the project for win32 applications?

i think you cannot rebuild it with win32 application, the author said it isnot support the 32 bit process.....
